version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: twitterclone_dev_db
      POSTGRES_USER: twitterclone_dev
      POSTGRES_PASSWORD: twitterclone_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
