services:
  - type: web
    name: twitterclone
    runtime: python
    buildCommand: "poetry install --no-root"
    startCommand: "poetry run gunicorn twitterclone.wsgi --bind 0.0.0.0:10000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: twitterclone-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
databases:
  - name: twitterclone-db
    plan: free
