name: Django CI

on:
  push:
    branches:
      - main
      - workflows
  pull_request:
    branches:
      - main
      - workflows

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: django
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U django"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Debug file structure
        run: ls -R

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run migrations
        env:
          DATABASE_URL: postgres://django:django@localhost:5432/test_db
        run: |
          poetry run python manage.py migrate

      - name: Run tests
        env:
          DATABASE_URL: postgres://django:django@localhost:5432/test_db
        run: |
          poetry run python manage.py test
